# Generated by Django 5.1.1 on 2024-10-05 20:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogchecker", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="blog",
            name="author",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="content",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="language",
        ),
        migrations.RemoveField(
            model_name="blog",
            name="title",
        ),
        migrations.AddField(
            model_name="blog",
            name="url",
            field=models.URLField(default="", unique=True),
        ),
        migrations.AlterField(
            model_name="blog",
            name="is_public",
            field=models.BooleanField(default=True),
        ),
    ]
