# Generated by Django 5.1.1 on 2024-10-05 22:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogchecker", "0003_rename_blog_post_e2brunoutput_blog_blogcoderecipe"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="e2brunoutput",
            name="blog",
        ),
        migrations.AddField(
            model_name="e2brunoutput",
            name="blog_code_recipe",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="e2b_runs",
                to="blogchecker.blogcoderecipe",
            ),
        ),
    ]
