# Generated by Django 5.1.1 on 2024-10-06 00:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogchecker", "0005_blog_is_analyzed"),
    ]

    operations = [
        migrations.AddField(
            model_name="e2brunoutput",
            name="code_interpreter_hostname",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
