# Generated by Django 5.1.1 on 2024-10-08 21:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogchecker", "0006_e2brunoutput_code_interpreter_hostname"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="e2brunoutput",
            name="code_content",
        ),
        migrations.RemoveField(
            model_name="e2brunoutput",
            name="code_interpreter_hostname",
        ),
        migrations.RemoveField(
            model_name="e2brunoutput",
            name="description",
        ),
        migrations.RemoveField(
            model_name="e2brunoutput",
            name="entrypoint",
        ),
        migrations.RemoveField(
            model_name="e2brunoutput",
            name="language",
        ),
        migrations.RemoveField(
            model_name="e2brunoutput",
            name="published_at",
        ),
        migrations.RemoveField(
            model_name="e2brunoutput",
            name="success_criteria",
        ),
        migrations.RemoveField(
            model_name="e2brunoutput",
            name="title",
        ),
    ]
