# Generated by Django 5.1.1 on 2024-10-08 22:45

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("blogchecker", "0007_remove_e2brunoutput_code_content_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogcoderecipe",
            name="code_content",
            field=tinymce.models.HTMLField(),
        ),
    ]
