# Generated by Django 5.1.1 on 2024-10-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("blogchecker", "0008_alter_blogcoderecipe_code_content"),
    ]

    operations = [
        migrations.AddField(
            model_name="e2brunoutput",
            name="code_interpreter_hostname",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
